### PR TITLE
chore: prefer atomic.Pointer to atomic.Value

### PR DESCRIPTION
**Pull request by arnehormann**
This improves the situation by closing down the api and enforcing the required type.
It also slightly reduces allocations and memory use and - at least on my system - improves benchmarking time for the whole system from 35.788s to 32.588s (but only one run each and 2 days apart...).

### CODE REVIEW

**Review by timbray — APPROVED** [review]
Looks good to me. 
I wonder how I managed to not notice atomic.Pointer. Will leave a little while for pushing in case one of our other Go experts has an opinion.

**Comment by timbray** [comment]
BTW @arnehormann unless you object I will add you as contributor so you can run CI etc.

**Comment by arnehormann** [comment]
I don't object, but I don't know how often or how much I'll contribute after these PRs. Not that I won't, just that I don't know yet.

**Comment by timbray** [comment]
> I don't object, but I don't know how often or how much I'll contribute after these PRs. Not that I won't, just that I don't know yet. Thanks for your trust!

Well, as long as you have a couple of PRs in flight, you should be able to trigger the CI/CD without waiting for me to wake up in West Coast time and press the "Run CI" button.

**Comment by arnehormann** [comment]
> > I don't object, but I don't know how often or how much I'll contribute after these PRs. Not that I won't, just that I don't know yet. Thanks for your trust!
> 
> Well, as long as you have a couple of PRs in flight, you should be able to trigger the CI/CD without waiting for me to wake up in West Coast time and press the "Run CI" button.

That... is indeed quite nice. I needed a lot of roundtrips until I broke no rules and a rather stupid blindness bug was squashed in numbits...

**Comment by timbray** [comment]
> That... is indeed quite nice. I needed a lot of roundtrips until I broke no rules and a rather stupid blindness bug was squashed in numbits...

Our CI/CD setup is due to @embano1 and is quite effective, although as you'll see if you watch the ignore-case PR, it's got one problem that I'm having trouble working around.

**Comment by embano1** [comment]
> Looks good to me. I wonder how I managed to not notice atomic.Pointer.

They were introduced somewhat "recently" in Go 1.19, and `atomic.Value` has been around for longer (and during the time you created Quamina) - so there's no-one to blame here ;)

+1 on using `atomic.Pointer`

**Comment by timbray** [comment]
Hey @arnehormann I have an overall performance test script and the change to atomic.Pointer led to an 0.52% improvement overall and 1.37% in the most common case.

**Comment by arnehormann** [comment]
That sounds wonderful! Is have hoped for more, but it's a lot for such a small change. Also, live by a thousand paper-mends or somesuch

**Pull request merged**
