### PR TITLE
chore: flatten_json: fix formatting

### PR DESCRIPTION
**Pull request by yosiat**
Signed-off-by: Yosi Attias <yosy101@gmail.com>

### CODE REVIEW

**Review by embano1 — APPROVED** [review]
LGTM

**Review by timbray — CHANGES_REQUESTED** [review]
This is blocked because it contains unsigned commits.  Sorry, I have no idea how to fix this, maybe have to re-spin the PR?

**Comment by yosiat** [comment]
@timbray what do you mean? I have signed this commit..

```
Signed-off-by: Yosi Attias <yosy101@gmail.com>
```

**Review by timbray — DISMISSED** [review]

**Comment by timbray** [comment]
I'm looking at this PR, https://github.com/timbray/quamina/pull/152, and seeing “Merging is blocked”, in red letters. Maybe I'm missing something obvious?

**Comment by yosiat** [comment]
@timbray It was issue on my side.. needed to configure gpg keys.. now we should be able to merge.

**Comment by timbray** [comment]
OK, done.

**Pull request merged**
